//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEmpaques.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boxlist
    {
        public int id { get; set; }
        public int idInventario { get; set; }
        public string Presupuesto { get; set; }
        public string Descripcion { get; set; }
        public string Dimensiones { get; set; }
        public string OrdenFabricacion { get; set; }
        public int idEmpaque { get; set; }
        public Nullable<int> Autonumerico { get; set; }
    
        public virtual Empaque Empaque { get; set; }
        public virtual PedidoInventario PedidoInventario { get; set; }
    }
}
