//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEmpaques.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empaque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empaque()
        {
            this.Boxlist = new HashSet<Boxlist>();
        }
    
        public int id { get; set; }
        public string Presupuesto { get; set; }
        public string OrdenFabricacion { get; set; }
        public int Consecutivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boxlist> Boxlist { get; set; }
    }
}
