//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEmpaques.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InnoWinEntities : DbContext
    {
        public InnoWinEntities()
            : base("name=InnoWinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boxlist> Boxlist { get; set; }
        public virtual DbSet<Empaque> Empaque { get; set; }
        public virtual DbSet<Impresora> Impresora { get; set; }
        public virtual DbSet<PedidoInventario> PedidoInventario { get; set; }
    }
}
