//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEmpaques.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoInventario()
        {
            this.Boxlist = new HashSet<Boxlist>();
        }
    
        public int id { get; set; }
        public string Presupuesto { get; set; }
        public string Pedido { get; set; }
        public int Autonumerico { get; set; }
        public string Descripcion { get; set; }
        public string Dimensiones { get; set; }
        public Nullable<int> Ancho { get; set; }
        public Nullable<int> Alto { get; set; }
        public string OrdenFabricacion { get; set; }
        public bool Empacado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boxlist> Boxlist { get; set; }
    }
}
